### PR TITLE
Make loglevel thread safe

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by carsonreinke** [comment]
@n-rodriguez Not sure this does what you want it to do:

```
$ > logger.level == Logger::INFO
 => true 
$ > Thread.new{logger.level = Logger::FATAL}
 => #<Thread:0x00000001b3d750@(irb):9 run> 
$ > logger.level == Logger::INFO
 => true 
```

Why not just a mutex on the level method?

**Comment by n-rodriguez** [comment]
> Why not just a mutex on the level method?

I don't know :) The main goal was to add test for this [PR](https://github.com/crohr/syslogger/pull/18) and see if it was still relevant.

**Comment by carsonreinke** [comment]
Probably this, but I guess what would be the point.  These methods surmount to basically setters.

```ruby
def level=(level)
  synchronize do
    @level = sanitize_level(level)
  end
end

def level()
  synchronize do
    @level
  end
end
```

**Comment by n-rodriguez** [comment]
```
$ > logger.level == Logger::INFO
 => true 
$ > Thread.new{logger.level = Logger::FATAL}
 => #<Thread:0x00000001b3d750@(irb):9 run> 
$ > logger.level == Logger::INFO
 => true 
```
I'm sorry, but after re-read it, it's actually right for me. The goal is to change the loglevel in an other thread than the current thread.

Here what's happening :

```
$ > logger.level == Logger::INFO  # this happens in the irb thread/process/whatever
 => true 
$ > Thread.new{logger.level = Logger::FATAL} # here you set a different loglevel in a new thread
# Here a better test would have been: 
$ > Thread.new{logger.level = Logger::FATAL; puts logger.level == Logger::INFO}
 => #<Thread:0x00000001b3d750@(irb):9 run> # here the thread is created, but not really started untill you call join (https://ruby-doc.org/core-2.2.0/Thread.html), so this will never be run
$ > logger.level == Logger::INFO # you're back in the irb thread/process
 => true 
```

**Comment by carsonreinke** [comment]
@n-rodriguez I am having hard time understanding the use case for that.  Why would not just create another logger for the thread?

**Comment by crohr** [comment]
Hello, sorry for my late involvement in this issue, and thanks @n-rodriguez for the work.

Re-reading the original PR, I believe the goal is to make the loglevel setter thread-safe. As such I'm not sure we need to care about allowing a different log level per thread, and we should probably go with just synchronizing the setter (as per @carsonreinke suggestion) to make sure we don't have race-conditions among multiple threads.

@geraud was your goal to really have a per-thread loglevel?

**Pull request closed without merging**
